language: csharp
solution: lab3.sln
install:
  - nuget restore lab3.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug lab3.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Router-Administration-System/RouterTests/bin/Debug/RouterTests.dll
